image:
  file: .gitpod.Dockerfile
tasks:
  - init: make dep && abtnode init -f --mode debug && cp .env.bac .env
    command: abtnode start && blocklet dev
ports:
  - port: 8080
    onOpen: ignore
  - port: 8089
    onOpen: ignore
  - port: 8090
    onOpen: ignore
  - port: 3030
    onOpen: ignore
